global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'greengage-monitor'

scrape_configs:
  - job_name: 'greengage-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['greengage-exporter:8080']
        labels:
          cluster: 'main'